### ISSUE TITLE
US 7 - Merchant Items Show Page

### ISSUE THREAD

**Issue by KatieLonsdale** [KatieLonsdale/little-esty-shop#12]
As a merchant,
When I click on the name of an item from the merchant items index page,
Then I am taken to that merchant's item's show page (/merchants/merchant_id/items/item_id)
And I see all of the item's attributes including:

- Name
- Description
- Current Selling Price

**Comment by CrowRising** [comment]
make a plan for each part of this test break it in to smaller pieces and set a timer for each piece

**Comment by CrowRising** [comment]
I MESSED UP y'all I did this whole user story in the wrong branch, it is in user story 6.
Don't it just figure. 
If there is an easy way to remedy this please let me know and I will!
